### ISSUE TITLE
使用视频预览出现错误代码后闪退

### ISSUE THREAD

**Issue by WisdomDevils** [COLOR-SKY/DialogueExtractor#1]
Traceback (most recent call last):
  File "D:\工具\DialogueExtractor-master\DialogueExtractor-master\DialogueExtractor_ch\DialogueExtractor.py", line 665, in <lambda>
    self.PerviewButton.clicked.connect(lambda: self.previewSelected())
  File "D:\工具\DialogueExtractor-master\DialogueExtractor-master\DialogueExtractor_ch\DialogueExtractor.py", line 274, in previewSelected
    for files in os.listdir(dir):
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: './temp/'

**Comment by WisdomDevils** [comment]
最终发现是ffmpeg的路径有中文名
修改路径和环境变量后成功运行
