### ISSUE TITLE
Failed to launch in python venv

### ISSUE THREAD

**Issue by wnpllrzodiac** [COLOR-SKY/DialogueExtractor#10]
```
python DialogueExtractor.py
C:\work\DialogueExtractor\DialogueExtractor_ch\DialogueExtractor.py:335: SyntaxWarning: invalid escape sequence '\s'
  punct = ".,。，?!？！\s\r\n"
Traceback (most recent call last):
<unknown>:191: SyntaxWarning: invalid escape sequence '\s'
  File "C:\work\DialogueExtractor\DialogueExtractor_ch\DialogueExtractor.py", line 145, in <module>
    class Ui_MainWindow(object):
    ...<543 lines>...
            self.tableWidget.setSortingEnabled(__sortingEnabled)
  File "C:\work\DialogueExtractor\DialogueExtractor_ch\DialogueExtractor.py", line 146, in Ui_MainWindow
    projectSetup = ProjectSetup()
  File "C:\work\DialogueExtractor\DialogueExtractor_ch\DialogueExtractor.py", line 60, in __init__
    data = json.loads(s)
  File "C:\Users\vmuser\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\vmuser\AppData\Local\Programs\Python\Python313\Lib\json\decoder.py", line 344, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vmuser\AppData\Local\Programs\Python\Python313\Lib\json\decoder.py", line 362, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
```

**Comment by wnpllrzodiac** [comment]
removed empty line in config.json, solved problem
