### ISSUE TITLE
命令行导入DialogueExtractor.py后报错

### ISSUE THREAD

**Issue by levingab** [COLOR-SKY/DialogueExtractor#4]
Traceback (most recent call last):
  File "D:\Python\DialogueExtractor-master\DialogueExtractor-master\DialogueExtractor_ch\DialogueExtractor.py", line 145, in <module>
    class Ui_MainWindow(object):
  File "D:\Python\DialogueExtractor-master\DialogueExtractor-master\DialogueExtractor_ch\DialogueExtractor.py", line 146, in Ui_MainWindow
    projectSetup = ProjectSetup()
  File "D:\Python\DialogueExtractor-master\DialogueExtractor-master\DialogueExtractor_ch\DialogueExtractor.py", line 60, in __init__
    data = json.loads(s)
  File "D:\Anacoda\envs\Dex\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "D:\Anacoda\envs\Dex\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Anacoda\envs\Dex\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

**Comment by COLOR-SKY** [comment]
可能configure.json文件包含无法识别的字段，大多数情况是文件内容包含了emoji，unicode这类文本。请检查以下。
